config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#show"

  resources :time_entries, only: [:index, :new, :create, :destroy]

  get 'sign_in', action: :new, controller: :sessions
  get 'sign_in_callback', action: :create, controller: :sessions
  get 'sign_out', action: :destroy, controller: :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/projects.rb
class Projects
  include ActiveModel::Model

  def get(headers)
    response = HTTParty.get("https://api.harvestapp.com/v2/users/me/project_assignments", headers: headers)
    {
      projects: response["project_assignments"].map {|proj|
                  [
                    proj["project"]["name"], proj["project"]["id"].to_s
                  ]
                }.sort_by {|proj| proj[0] },
      tasks:    response["project_assignments"][0]["task_assignments"].map {|ta|
                  [
                    ta["task"]["name"], ta["task"]["id"].to_s
                  ]
                }.sort_by {|proj| proj[0] }
    }
  end
end

app/models/time_entry_bulk_creator.rb
class TimeEntryBulkCreator
  include ActiveModel::Model

  attr_accessor :start_date, :end_date, :start_time, :end_time, :project_id, :task_id

  validates :start_date, :end_date, :start_time, :end_time, :project_id, :task_id, presence: true
  validates_comparison_of :start_date, less_than: -> (record) { record.end_date }, message: "must be before end date"
  validates_comparison_of :start_time, less_than: -> (record) { record.end_time }, message: "must be before end time"

  def initialize(args = {})
    args[:start_date] ||= Date.today
    args[:start_time] ||= Time.new(2000, 1, 1, 9, 0)
    args[:end_time]   ||= Time.new(2000, 1, 1, 17, 0)
    args[:project_id] ||= 32294801
    args[:task_id]    ||= 18476820
    args.each do |k,v|
      instance_variable_set("@#{k}", v) unless v.nil?
    end
  end

  def send(current_user)
    return nil unless valid?
    result = []
    date_range.each do |date|
      next if date.saturday? || date.sunday?
      response = HTTParty.post("https://api.harvestapp.com/v2/time_entries",
        headers: current_user[:headers],
        body: {
          "user_id": current_user[:user_id],
          "project_id": project_id,
          "task_id": task_id,
          "spent_date": date.strftime("%F"),
          "started_time": Time.parse(start_time).strftime("%-l:%M%P"),
          "ended_time": Time.parse(end_time).strftime("%-l:%M%P"),
        }.to_json
      )
      result << project_id + ' ' + task_id + ' ' + date.strftime("%F") + ' ' + Time.parse(start_time).strftime("%-l:%M%P") + ' ' + Time.parse(end_time).strftime("%-l:%M%P")
      sleep 0.5
    end
    result
  end

  private

  def date_range
    Date.parse(start_date)..Date.parse(end_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Cookies

  before_action :clear_sessions
  before_action :load_user_info

  private

  SESSION_MAX = 20

  def clear_sessions
    # Delete all sessions
    # ActiveRecord::Base.connection.exec_delete("DELETE FROM sessions"); return

    # Delete sessions older than an hour
    # ActiveRecord::Base.connection.exec_delete("DELETE FROM sessions WHERE created_at < '#{(DateTime.current - 1.hour).to_fs(:db)}'"); return

    # Keep the last SESSION_MAX sessions in memory
    nb_of_sessions = ActiveRecord::Base.connection.exec_query("SELECT COUNT(id) FROM sessions").first.first.last
    return if nb_of_sessions < SESSION_MAX
    id = ActiveRecord::Base.connection.exec_query("SELECT id FROM sessions ORDER BY created_at DESC LIMIT #{SESSION_MAX}").rows.last.first
    ActiveRecord::Base.connection.exec_delete("DELETE FROM sessions WHERE id < #{id}")
  end

  def load_user_info
    if session[:user_info].nil? && params[:controller] != "sessions"
      redirect_to sign_in_path
      return
    end
    @current_user = session[:user_info]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    redirect_to sign_in_path and return if @current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    redirect_to root_path and return if params["error"] == ("access_denied")

    @result = params.permit(:code, :scope)
    user_info = {}
    user_info[:code] = @result[:code]
    user_info[:scope] = @result[:scope]
    user_info[:account_id] = @result[:scope].split(":")[1]

    response = HTTParty.post("https://id.getharvest.com/api/v2/oauth2/token",
                             headers: {
                               "User-Agent" => ApplicationHelper::APP_NAME,
                               "Content-Type" => "application/json",
                             },
                             body: {
                               "code": user_info[:code],
                               "client_id": ApplicationHelper::CLIENT_ID,
                               "client_secret": ApplicationHelper::CLIENT_SECRET,
                               "grant_type": "authorization_code",
                             }.to_json)

    user_info[:access_token] = response["access_token"]
    user_info[:refresh_token] = response["refresh_token"]
    user_info[:token_type] = response["token_type"]
    user_info[:expires_at] = (DateTime.now + response["expires_in"].seconds).to_s
    user_info[:headers] = {
      "Authorization" => "Bearer " + user_info[:access_token],
      "Harvest-Account-ID" => user_info[:account_id],
      "User-Agent" => ApplicationHelper::APP_NAME,
      "Content-Type" => "application/json",
    }

    http_response = HTTParty.get("https://api.harvestapp.com/api/v2/users/me", headers: user_info[:headers])
    user_info[:first_name] = http_response["first_name"]
    user_info[:last_name] = http_response["last_name"]
    user_info[:email] = http_response["email"]
    user_info[:user_id] = http_response["id"]
    user_info[:avatar_url] = http_response["avatar_url"]

    session[:user_info] = user_info.dup
    redirect_to root_path
  end

  def destroy
    session.delete(:user_info)
    redirect_to root_path
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    http_response = HTTParty.get("https://api.harvestapp.com/v2/time_entries", headers: @current_user[:headers])
    @entries = http_response["time_entries"].take(20)
  end

  def new
    @tebc = TimeEntryBulkCreator.new
    @projects = Projects.new.get(@current_user[:headers])
  end

  def create
    @tebc = TimeEntryBulkCreator.new(tebc_params)
    @result = @tebc.send(@current_user)

    unless @result
      @projects = Projects.new.get(@current_user[:headers])
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    url = "https://api.harvestapp.com/v2/time_entries/%d" % params[:id]
    response = HTTParty.delete(url, headers: @current_user[:headers])
    redirect_to time_entries_path
  end

  private

  def tebc_params
    params.require(:time_entry_bulk_creator)
      .permit(:start_date, :end_date, :start_time, :end_time, :project_id, :task_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  CLIENT_ID     = Rails.application.credentials[:harvest][Rails.env][:client_id]
  CLIENT_SECRET = Rails.application.credentials[:harvest][Rails.env][:client_secret]
  APP_NAME      = Rails.application.credentials[:harvest][Rails.env][:app_name]
  AUTH_URL      = "https://id.getharvest.com/oauth2/authorize?client_id=" + CLIENT_ID + "&response_type=code"
end

app/views/home/show.html.erb
<%= link_to "Latest time entries", time_entries_path, data: { turbo_frame: "main" } %> |
<%= link_to "Create time entries", new_time_entry_path, data: { turbo_frame: "main" } %>

<hr>

<%= turbo_frame_tag "main" do %>
<% end %>

app/views/layouts/_header.html.erb
<h1>Harvest App</h1>
<% if @current_user.present? %>
  <p>Hi <%= @current_user[:first_name] %> <%= @current_user[:last_name] %>! <%= link_to "(sign out)" , sign_out_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HarvestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="color-scheme" content="light dark" />
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag "https://cache.harvestapp.com/favicon.ico" %>
  </head>

  <body>
    <header class="container">
      <%= render partial: "layouts/header" %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/time_entries/create.html.erb
<%= turbo_frame_tag "main" do %>
  <h3>Entries added:</h3>
  <% @result.each do |msg| -%>
    <%= content_tag :div, msg %>
  <% end -%>
<% end %>

app/views/time_entries/index.html.erb
<%= turbo_frame_tag "main" do %>
  <section>
    <h2>Latest Entries</h2>
    <div class="overflow-auto">
      <table class="striped">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Nb. of Hours</th>
            <th scope="col">Client</th>
            <th scope="col">Project</th>
            <th scope="col">Task</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @entries.each do |e| %>
            <tr>
              <td><%= e["spent_date"] %></td>
              <td><%= e["hours"] %></td>
              <td><%= e["client"]["name"] %></td>
              <td><%= e["project"]["name"] %></td>
              <td><%= e["task"]["name"] %></td>
              <td><%= link_to "Delete", time_entry_path(e["id"]), data: { "turbo-method": :delete } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
<% end %>

app/views/time_entries/new.html.erb
<%= turbo_frame_tag "main" do %>
  <section>
    <h2>Create time entries</h2>
    <%= form_with(model: @tebc, method: :post, url: time_entries_path, data: { controller: "form" }) do |f| %>
      <fieldset class="grid">
        <label>
          From
          <%= f.date_field :start_date %>
        </label>
        <label>
          Until
          <%= f.date_field :end_date %>
      </fieldset>
      <fieldset class="grid">
        <label>
          Start Time
          <%= f.time_field :start_time %>
        </label>
        <label>
          End Time
          <%= f.time_field :end_time %>
        </label>
      </fieldset>
      <fieldset class="grid">
        <label>
          Project
          <%= f.select :project_id, @projects[:projects], include_blank: "Select project" %>
        </label>
        <label>
          Task
          <%= f.select :task_id, @projects[:tasks], include_blank: "Select task" %>
        </label>
      </fieldset>
      <%= f.submit "Create" %>
    <% end %>

    <% @tebc.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </section>
<% end %>